language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - pytest --cov

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

codecov: true

services:
  - postgresql

before_script:
  - psql -c 'create database dating_django;' -U postgres