version: '3.8'

services:

  db:
    container_name: dating-django-db
    environment:
      - POSTGRES_PASSWORD=postgresrootpass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dating_django
    image: postgres:13.2
    ports:
      - "5432:5432"
    volumes:
      - .:/app/
      - ./database-dump-restore.sh:/docker-entrypoint-initdb.d/database-dump-restore.sh
