version: '3.8'

services:

  dating-django-db:
    container_name: dating-django-db
    environment:
      - POSTGRES_PASSWORD=postgresrootpass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dating_django
    image: postgres:13.2
    ports:
      - "5432:5432"
    volumes:
      - .:/app/
      - ./database-dump-restore.sh:/docker-entrypoint-initdb.d/database-dump-restore.sh

  dating-redis:
    container_name: dating-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - .:/app/

  dating-django:
    build: .
    command: python manage.py runserver
    container_name: dating-django
    depends_on:
      - dating-django-db
    network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
