# Generated by Django 3.2 on 2021-04-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Client',
            name='avatar',
            field=models.ImageField(default='uploads/avatars/no-photo.png', upload_to='uploads/avatars/'),
        ),
    ]
