# Generated by Django 3.2 on 2021-04-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0004_auto_20210429_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='coord_x',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='долгота'),
        ),
        migrations.AddField(
            model_name='client',
            name='coord_y',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='широта'),
        ),
    ]
