# Generated by Django 3.2 on 2021-05-03 12:01

import dating.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0005_auto_20210430_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/no-photo.png', upload_to=dating.utils.utils.get_upload_to, verbose_name='файл аватара'),
        ),
    ]
