# Generated by Django 3.2 on 2021-05-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='no-photo.png', null=True, upload_to='', verbose_name='изображение'),
        ),
    ]
