# Generated by Django 3.2 on 2021-05-06 08:08

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='no-photo.png', null=True, upload_to=utils.utils.get_upload_to, verbose_name='файл изображения'),
        ),
    ]
